# Generated by Django 5.0.4 on 2024-05-08 02:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalIndicador',
            new_name='HistoricalIndicator',
        ),
        migrations.RenameModel(
            old_name='Indicador',
            new_name='Indicator',
        ),
    ]
