# Generated by Django 5.0.4 on 2024-05-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_historicalindicador_historicalindicator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalindicator',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Indicador de Oferta', 'verbose_name_plural': 'historical Indicadores de Ofertas'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Indicador de Oferta', 'verbose_name_plural': 'Indicadores de Ofertas'},
        ),
    ]
