# Generated by Django 5.0.4 on 2024-05-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_historicalindicator_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproduct',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='historicalcategoryproduct',
            name='measure_unit',
        ),
    ]
