/**
 * All user-facing strings in the application.
 * Organized by page/component for future i18n toggle (EN/ES).
 */

export const strings = {
  // === NAVBAR ===
  nav: {
    brand: 'URBAN ATTIC',
    catalog: 'CATALOG',
    newDrops: 'NEW DROPS',
    login: 'LOGIN',
    register: 'REGISTER',
    profile: 'PROFILE',
    myOrders: 'MY ORDERS',
    logout: 'LOGOUT',
    searchPlaceholder: 'SCAN CATALOG...',
    searchButton: 'SCAN',
    closeFilters: 'CLOSE FILTERS',
    filters: 'FILTERS',
  },

  // === FOOTER ===
  footer: {
    brand: 'URBAN ATTIC',
    tagline: 'STREETWEAR BORN IN ASUNCION. DESIGNED FOR THE CONCRETE LANDSCAPE.',
    // tagline_es: 'STREETWEAR NACIDO EN ASUNCION. DISEÑADO PARA EL PAISAJE DE CONCRETO.',
    shop: 'SHOP',
    company: 'COMPANY',
    connect: 'CONNECT',
    catalog: 'CATALOG',
    men: 'MEN',
    women: 'WOMEN',
    unisex: 'UNISEX',
    about: 'ABOUT',
    contact: 'CONTACT',
    terms: 'TERMS',
    privacy: 'PRIVACY',
    instagram: 'INSTAGRAM',
    tiktok: 'TIKTOK',
    email: 'EMAIL',
    established: 'EST. 2018 / ASUNCION',
  },

  // === HOME PAGE ===
  home: {
    heroHeadline: 'STREET LEVEL ONLY',
    heroSubtitle: 'COMFORTABLE, MODERN, AND AUTHENTIC URBAN FASHION FROM ASUNCION.',
    // heroSubtitle_es: 'MODA URBANA COMODA, MODERNA Y AUTENTICA DESDE ASUNCION.',
    shopNow: 'SHOP NOW',
    // shopNow_es: 'COMPRAR AHORA',
    curatedSelection: 'CURATED SELECTION',
    // curatedSelection_es: 'SELECCION CURADA',
    latestDrops: 'LATEST DROPS',
    // latestDrops_es: 'ULTIMOS LANZAMIENTOS',
    viewAll: 'VIEW ALL',
    // viewAll_es: 'VER TODO',
    ourStory: 'OUR STORY',
    // ourStory_es: 'NUESTRA HISTORIA',
    brandHeadline: 'BORN IN THE STREETS OF ASUNCION.',
    // brandHeadline_es: 'NACIDO EN LAS CALLES DE ASUNCION.',
    brandBio: 'Founded in 2018, Urban Attic was born as a youth clothing store inspired by urban trends, skate culture, and alternative music. Comfortable, modern, and accessible clothing for a new generation.',
    brandBio_es: 'Fundada en 2018, Urban Attic nace como una tienda de ropa juvenil inspirada en las tendencias urbanas, la cultura del skate y la musica alternativa. Prendas comodas, modernas y accesibles para una nueva generacion.',
    exploreCatalog: 'EXPLORE CATALOG',
    // exploreCatalog_es: 'EXPLORAR CATALOGO',
    joinNetwork: 'JOIN THE NETWORK.',
    // joinNetwork_es: 'UNITE A LA RED.',
    newsletterSubtitle: 'DROPS, DEALS, AND STREET CULTURE. DELIVERED WEEKLY.',
    // newsletterSubtitle_es: 'LANZAMIENTOS, OFERTAS Y CULTURA URBANA. CADA SEMANA.',
    subscribe: 'SUBSCRIBE',
    // subscribe_es: 'SUSCRIBIRSE',
    emailPlaceholder: 'YOUR@EMAIL.COM',
    welcomeToast: 'Welcome to the network.',
    // welcomeToast_es: 'Bienvenido a la red.',
    categoryMen: 'MEN',
    // categoryMen_es: 'HOMBRES',
    categoryWomen: 'WOMEN',
    // categoryWomen_es: 'MUJERES',
    categoryUnisex: 'UNISEX',
  },

  // === CATALOG / PRODUCTS PAGE ===
  catalog: {
    title: 'THE CATALOG',
    // title_es: 'EL CATALOGO',
    subtitle: 'Curated for the concrete landscape.',
    // subtitle_es: 'Curado para el paisaje de concreto.',
    established: 'EST. 2018 / ASUNCION',
    scanPlaceholder: 'SCAN...',
    // scanPlaceholder_es: 'BUSCAR...',
    objectsFound: 'OBJECTS FOUND',
    // objectsFound_es: 'OBJETOS ENCONTRADOS',
    categories: 'CATEGORIES',
    // categories_es: 'CATEGORIAS',
    priceRange: 'PRICE RANGE',
    // priceRange_es: 'RANGO DE PRECIO',
    minPrice: 'MIN PRICE',
    maxPrice: 'MAX PRICE',
    resetFilters: 'RESET FILTERS',
    // resetFilters_es: 'LIMPIAR FILTROS',
    prev: 'PREV',
    next: 'NEXT',
    soldOut: 'SOLD OUT',
    // soldOut_es: 'AGOTADO',
    newDrop: 'NEW DROP',
    // newDrop_es: 'NUEVO',
    noProducts: 'No products found',
    // noProducts_es: 'No se encontraron productos',
  },

  // === PRODUCT DETAIL ===
  product: {
    backToCatalog: 'BACK TO CATALOG',
    // backToCatalog_es: 'VOLVER AL CATALOGO',
    color: 'COLOR',
    size: 'SIZE',
    // size_es: 'TALLA',
    quantity: 'QUANTITY',
    // quantity_es: 'CANTIDAD',
    secure: 'SECURE',
    // secure_es: 'ASEGURAR',
    securing: 'SECURING...',
    inStock: 'IN STOCK',
    // inStock_es: 'EN STOCK',
    soldOut: 'SOLD OUT',
    // soldOut_es: 'AGOTADO',
    notFound: 'PRODUCT NOT FOUND',
    noImage: 'NO IMAGE',
  },

  // === CART ===
  cart: {
    title: 'YOUR',
    titleAccent: 'HAUL',
    // title_es: 'TU',
    // titleAccent_es: 'CARGA',
    subtitle: 'LOCKED AND LOADED // SECURE YOUR SELECTIONS',
    // subtitle_es: 'LISTO Y CARGADO // ASEGURA TUS SELECCIONES',
    empty: 'YOUR HAUL IS EMPTY',
    // empty_es: 'TU CARGA ESTA VACIA',
    emptySubtitle: 'TIME TO FILL IT UP',
    // emptySubtitle_es: 'ES HORA DE LLENARLO',
    viewAllObjects: 'VIEW ALL OBJECTS',
    // viewAllObjects_es: 'VER TODOS LOS OBJETOS',
    hookupCode: 'GOT A HOOKUP CODE?',
    // hookupCode_es: 'TENES UN CODIGO?',
    enterCode: 'ENTER CODE',
    apply: 'APPLY',
    // apply_es: 'APLICAR',
    damage: 'DAMAGE',
    orderSummary: 'ORDER SUMMARY BREAKDOWN',
    rawSub: 'RAW SUB',
    logistics: 'LOGISTICS',
    free: 'FREE',
    // free_es: 'GRATIS',
    total: 'TOTAL',
    proceedToCheckout: 'PROCEED TO CHECKOUT',
    // proceedToCheckout_es: 'PROCEDER AL PAGO',
    secureNode: 'SECURE ENCRYPTED NODE',
    deployment: '48H DEPLOYMENT',
    clearHaul: 'CLEAR HAUL',
    // clearHaul_es: 'VACIAR CARGA',
    clearConfirm: 'Clear your entire haul?',
    // clearConfirm_es: 'Vaciar toda tu carga?',
    itemRemoved: 'Item removed from haul',
    haulCleared: 'Haul cleared',
    needAssistance: 'NEED ASSISTANCE? CONTACT SCANNERS',
  },

  // === AUTH ===
  auth: {
    loginTitle: 'LOGIN',
    // loginTitle_es: 'INICIAR SESION',
    loginDescription: 'Enter your email and password to access your account',
    // loginDescription_es: 'Ingresa tu email y contraseña para acceder a tu cuenta',
    registerTitle: 'REGISTER',
    // registerTitle_es: 'REGISTRARSE',
    registerDescription: 'Create a new account to start shopping',
    // registerDescription_es: 'Crea una cuenta nueva para empezar a comprar',
    emailLabel: 'EMAIL',
    passwordLabel: 'PASSWORD',
    // passwordLabel_es: 'CONTRASEÑA',
    firstNameLabel: 'FIRST NAME',
    // firstNameLabel_es: 'NOMBRE',
    lastNameLabel: 'LAST NAME',
    // lastNameLabel_es: 'APELLIDO',
    confirmPasswordLabel: 'CONFIRM PASSWORD',
    // confirmPasswordLabel_es: 'CONFIRMAR CONTRASEÑA',
    noAccount: "Don't have an account?",
    // noAccount_es: 'No tenes cuenta?',
    hasAccount: 'Already have an account?',
    // hasAccount_es: 'Ya tenes cuenta?',
  },

  // === PROFILE ===
  profile: {
    title: 'YOUR PROFILE',
    // title_es: 'TU PERFIL',
    accountInfo: 'ACCOUNT INFO',
    // accountInfo_es: 'INFO DE CUENTA',
    editProfile: 'EDIT PROFILE',
    // editProfile_es: 'EDITAR PERFIL',
    email: 'EMAIL',
    memberSince: 'MEMBER SINCE',
    // memberSince_es: 'MIEMBRO DESDE',
    firstName: 'FIRST NAME',
    lastName: 'LAST NAME',
    saveChanges: 'SAVE CHANGES',
    // saveChanges_es: 'GUARDAR CAMBIOS',
    saving: 'SAVING...',
  },

  // === ORDERS ===
  orders: {
    title: 'YOUR ORDERS',
    // title_es: 'TUS ORDENES',
    noOrders: 'NO ORDERS YET',
    // noOrders_es: 'AUN NO HAY ORDENES',
    startShopping: 'START SHOPPING',
    // startShopping_es: 'EMPEZAR A COMPRAR',
    orderNumber: 'ORDER #',
    date: 'DATE',
    // date_es: 'FECHA',
    status: 'STATUS',
    // status_es: 'ESTADO',
    items: 'ITEMS',
    total: 'TOTAL',
    actions: 'ACTIONS',
    // actions_es: 'ACCIONES',
    view: 'VIEW',
    // view_es: 'VER',
    cancelOrder: 'CANCEL ORDER',
    // cancelOrder_es: 'CANCELAR ORDEN',
    payNow: 'PAY NOW',
    // payNow_es: 'PAGAR AHORA',
  },

  // === CHECKOUT ===
  checkout: {
    title: 'CHECKOUT',
    // title_es: 'PAGO',
    shippingInfo: 'SHIPPING INFORMATION',
    // shippingInfo_es: 'INFORMACION DE ENVIO',
    shippingAddress: 'SHIPPING ADDRESS',
    // shippingAddress_es: 'DIRECCION DE ENVIO',
    orderNotes: 'ORDER NOTES (OPTIONAL)',
    // orderNotes_es: 'NOTAS DEL PEDIDO (OPCIONAL)',
    proceedToPayment: 'PROCEED TO PAYMENT',
    // proceedToPayment_es: 'PROCEDER AL PAGO',
    processing: 'PROCESSING...',
    successTitle: 'PAYMENT SUCCESSFUL!',
    // successTitle_es: 'PAGO EXITOSO!',
    successMessage: 'Your order has been confirmed and is now being processed. You will receive a confirmation email shortly.',
    // successMessage_es: 'Tu orden ha sido confirmada y esta siendo procesada. Recibiras un email de confirmacion en breve.',
    viewMyOrders: 'VIEW MY ORDERS',
    // viewMyOrders_es: 'VER MIS ORDENES',
    continueShopping: 'CONTINUE SHOPPING',
    // continueShopping_es: 'SEGUIR COMPRANDO',
    cancelledTitle: 'PAYMENT CANCELLED',
    // cancelledTitle_es: 'PAGO CANCELADO',
    cancelledMessage: 'Your payment was not completed. Your order is still pending and no charges were made.',
    // cancelledMessage_es: 'Tu pago no fue completado. Tu orden sigue pendiente y no se realizaron cargos.',
    tryAgain: 'TRY AGAIN',
    // tryAgain_es: 'INTENTAR DE NUEVO',
  },
} as const;

export type StringKeys = typeof strings;
